version: "3.8"

services:
  movipay-roaming:
    build: ./movipay/4/challenge
    ports:
      - "31336:31336"
    environment:
      FLAG: VTCH{r0am1ng_1d3nt1ty_n0t_r3b0und_t0_s3ss10n}
      PORT: "31336"
    restart: always

  stock-engine-race:
    build: ./vulnerability/race-withdrawal/2/challenge
    ports:
      - "31337:31337"
    environment:
      FLAG: VTCH{Ch3ck_TH3n_Deb!t_I5_not_4_7ran5@ctiON}
      PORT: "31337"
    restart: always

  hanbit-bank-uaf:
    build: ./vulnerability/bank-uaf/3/challenge
    ports:
      - "31338:31338"
    environment:
      FLAG: VTCH{Dan6l!n9_MeRgE_r3COrDs_reUs3d_8y_ADM1n_reVIew}
      PORT: "31338"
    restart: always

  pyjail-sandbox:
    build: ./misc/pyjail/1/challenge
    ports:
      - "31339:31339"
    environment:
      FLAG: VTCH{4st_w4lker_c4nt_st0p_th3_d4rk_dund3rs!!}
      PORT: "31339"
    restart: always

